// deck.sr.js — полный словарь сербского (ekavian latin)
// Версия 1.0

window.decks = window.decks || {};

window.decks.de_pronouns = [
  { id: 1,  word: "ja",       uk: "я",        ru: "я" },
  { id: 2,  word: "ti",       uk: "ти",       ru: "ты" },
  { id: 3,  word: "on",       uk: "він",      ru: "он" },
  { id: 4,  word: "ona",      uk: "вона",     ru: "она" },
  { id: 5,  word: "ono",      uk: "воно",     ru: "оно" },
  { id: 6,  word: "mi",       uk: "ми",       ru: "мы" },
  { id: 7,  word: "vi",       uk: "ви",       ru: "вы" },
  { id: 8,  word: "oni",      uk: "вони",     ru: "они" },
  { id: 9,  word: "moj",      uk: "мій",      ru: "мой" },
  { id: 10, word: "tvoj",     uk: "твій",     ru: "твой" },
  { id: 11, word: "njegov",   uk: "його",     ru: "его" },
  { id: 12, word: "njen",     uk: "її",       ru: "её" },
  { id: 13, word: "naš",      uk: "наш",      ru: "наш" },
  { id: 14, word: "vaš",      uk: "ваш",      ru: "ваш" },
  { id: 15, word: "njihov",   uk: "їхній",    ru: "их" },
  { id: 16, word: "ovaj",     uk: "цей",      ru: "этот" },
  { id: 17, word: "taj",      uk: "той (ближ.)", ru: "тот (ближ.)" },
  { id: 18, word: "onaj",     uk: "он той (дал.)", ru: "вон тот (дал.)" },
  { id: 19, word: "koji",     uk: "який",     ru: "какой/который" },
  { id: 20, word: "ko",       uk: "хто",      ru: "кто" },
  { id: 21, word: "šta",      uk: "що",       ru: "что" },
  { id: 22, word: "neko",     uk: "хтось",    ru: "кто-то" },
  { id: 23, word: "niko",     uk: "ніхто",    ru: "никто" },
  { id: 24, word: "nešto",    uk: "щось",     ru: "что-то" },
  { id: 25, word: "ništa",    uk: "нічого",   ru: "ничего" }
];

window.decks.de_numbers = [
  { id: 1,  word: "jedan",      uk: "один",        ru: "один" },
  { id: 2,  word: "dva",        uk: "два",         ru: "два" },
  { id: 3,  word: "tri",        uk: "три",         ru: "три" },
  { id: 4,  word: "četiri",     uk: "чотири",      ru: "четыре" },
  { id: 5,  word: "pet",        uk: "п’ять",       ru: "пять" },
  { id: 6,  word: "šest",       uk: "шість",       ru: "шесть" },
  { id: 7,  word: "sedam",      uk: "сім",         ru: "семь" },
  { id: 8,  word: "osam",       uk: "вісім",       ru: "восемь" },
  { id: 9,  word: "devet",      uk: "дев’ять",     ru: "девять" },
  { id: 10, word: "deset",      uk: "десять",      ru: "десять" },
  { id: 11, word: "jedanaest",  uk: "одинадцять",  ru: "одиннадцать" },
  { id: 12, word: "dvanaest",   uk: "дванадцять",  ru: "двенадцать" },
  { id: 13, word: "trinaest",   uk: "тринадцять",  ru: "тринадцать" },
  { id: 14, word: "četrnaest",  uk: "чотирнадцять",ru: "четырнадцать" },
  { id: 15, word: "petnaest",   uk: "п’ятнадцять", ru: "пятнадцать" },
  { id: 16, word: "šesnaest",   uk: "шістнадцять", ru: "шестнадцать" },
  { id: 17, word: "sedamnaest", uk: "сімнадцять",  ru: "семнадцать" },
  { id: 18, word: "osamnaest",  uk: "вісімнадцять",ru: "восемнадцать" },
  { id: 19, word: "devetnaest", uk: "дев’ятнадцять",ru: "девятнадцать" },
  { id: 20, word: "dvadeset",   uk: "двадцять",    ru: "двадцать" },
  { id: 21, word: "trideset",   uk: "тридцять",    ru: "тридцать" },
  { id: 22, word: "četrdeset",  uk: "сорок",       ru: "сорок" },
  { id: 23, word: "pedeset",    uk: "п’ятдесят",   ru: "пятьдесят" },
  { id: 24, word: "šezdeset",   uk: "шістдесят",   ru: "шестьдесят" },
  { id: 25, word: "sedamdeset", uk: "сімдесят",    ru: "семьдесят" },
  { id: 26, word: "osamdeset",  uk: "вісімдесят",  ru: "восемьдесят" },
  { id: 27, word: "devedeset",  uk: "дев’яносто",  ru: "девяносто" },
  { id: 28, word: "sto",        uk: "сто",         ru: "сто" },
  { id: 29, word: "hiljadu",    uk: "тисяча",      ru: "тысяча" },
  { id: 30, word: "prvi",       uk: "перший",      ru: "первый" },
  { id: 31, word: "drugi",      uk: "другий",      ru: "второй" },
  { id: 32, word: "treći",      uk: "третій",      ru: "третий" },
  { id: 33, word: "četvrti",    uk: "четвертий",   ru: "четвёртый" },
  { id: 34, word: "peti",       uk: "п’ятий",      ru: "пятый" },
  { id: 35, word: "poslednji",  uk: "останній",    ru: "последний" }
];

// === PREPOSITIONS ===
window.decks.de_prepositions = [
  { id: 1,  word: "u",        uk: "в",            ru: "в" },
  { id: 2,  word: "na",       uk: "на",           ru: "на" },
  { id: 3,  word: "sa",       uk: "з, разом з",   ru: "с, вместе с" },
  { id: 4,  word: "bez",      uk: "без",          ru: "без" },
  { id: 5,  word: "za",       uk: "для/за",       ru: "для/за" },
  { id: 6,  word: "od",       uk: "від",          ru: "от" },
  { id: 7,  word: "do",       uk: "до",           ru: "до" },
  { id: 8,  word: "kod",      uk: "у (в когось)", ru: "у, у кого-то" },
  { id: 9,  word: "po",       uk: "по",           ru: "по" },
  { id: 10, word: "pri",      uk: "при",          ru: "при" },
  { id: 11, word: "prema",    uk: "до/щодо",      ru: "к/по отношению к" },
  { id: 12, word: "kroz",     uk: "крізь",        ru: "через" },
  { id: 13, word: "iz",       uk: "з, із",        ru: "из" },
  { id: 14, word: "ispred",   uk: "перед",        ru: "перед" },
  { id: 15, word: "iza",      uk: "позаду",       ru: "за (сзади)" },
  { id: 16, word: "iznad",    uk: "над",          ru: "над" },
  { id: 17, word: "ispod",    uk: "під",          ru: "под" },
  { id: 18, word: "između",   uk: "між",          ru: "между" },
  { id: 19, word: "tokom",    uk: "протягом",     ru: "в течение" },
  { id: 20, word: "zbog",     uk: "через/заради", ru: "из-за" },
  { id: 21, word: "uprkos",   uk: "незважаючи на",ru: "несмотря на" },
  { id: 22, word: "oko",      uk: "біля/навколо", ru: "около/вокруг" },
  { id: 23, word: "pored",    uk: "поруч",        ru: "рядом с" },
  { id: 24, word: "preko",    uk: "через/поверх", ru: "через/поверх" },
  { id: 25, word: "među",     uk: "серед",        ru: "среди" },
  { id: 26, word: "van",      uk: "поза",         ru: "вне" },
  { id: 27, word: "unutar",   uk: "всередині",    ru: "внутри" },
  { id: 28, word: "napolju",  uk: "зовні",        ru: "снаружи" },
  { id: 29, word: "pre",      uk: "перед (час)",  ru: "до (по времени)" },
  { id: 30, word: "posle",    uk: "після",        ru: "после" },
  { id: 31, word: "za vreme", uk: "під час",      ru: "во время" },
  { id: 32, word: "usled",    uk: "внаслідок",    ru: "вследствие" },
  { id: 33, word: "radi",     uk: "задля",        ru: "ради" },
  { id: 34, word: "nasuprot", uk: "навпроти",     ru: "напротив" },
  { id: 35, word: "putem",    uk: "шляхом/через", ru: "путём/через" },
  { id: 36, word: "o",        uk: "про",          ru: "о" },
  { id: 37, word: "prema gore", uk: "вгору",      ru: "вверх" },
  { id: 38, word: "prema dole", uk: "вниз",       ru: "вниз" },
  { id: 39, word: "prema unutra", uk: "всередину",ru: "внутрь" },
  { id: 40, word: "prema napolje", uk: "назовні", ru: "наружу" }
];

// === CONJUNCTIONS ===
window.decks.de_conjunctions = [
  { id: 1,  word: "i",            uk: "і",             ru: "и" },
  { id: 2,  word: "ili",          uk: "або",           ru: "или" },
  { id: 3,  word: "ali",          uk: "але",           ru: "но" },
  { id: 4,  word: "jer",          uk: "бо/тому що",    ru: "ибо/потому что" },
  { id: 5,  word: "zato što",     uk: "тому що",       ru: "потому что" },
  { id: 6,  word: "da",           uk: "щоб/що",        ru: "чтобы/что" },
  { id: 7,  word: "ako",          uk: "якщо",          ru: "если" },
  { id: 8,  word: "iako",         uk: "хоча",          ru: "хотя" },
  { id: 9,  word: "dok",          uk: "поки/в той час як", ru: "пока/в то время как" },
  { id: 10, word: "pre nego što", uk: "перш ніж",      ru: "прежде чем" },
  { id: 11, word: "posle što",    uk: "після того як", ru: "после того как" },
  { id: 12, word: "čim",          uk: "щойно/як тільки", ru: "как только" },
  { id: 13, word: "da bi",        uk: "щоб",           ru: "чтобы" },
  { id: 14, word: "dakle",        uk: "отже",          ru: "итак" },
  { id: 15, word: "zato",         uk: "тому/тому-то",  ru: "поэтому" },
  { id: 16, word: "nego",         uk: "а (вместо)",    ru: "а (вместо этого)" },
  { id: 17, word: "međutim",      uk: "проте",         ru: "однако" },
  { id: 18, word: "što više",     uk: "чим більше",    ru: "чем больше" },
  { id: 19, word: "kao i",        uk: "а також",       ru: "а также" },
  { id: 20, word: "pa",           uk: "і/та/так",      ru: "и/да/так" }
];

// === PARTICLES ===
window.decks.de_particles = [
  { id: 1,  word: "baš",     uk: "саме/прямо",      ru: "прямо/именно" },
  { id: 2,  word: "već",     uk: "вже/та й",        ru: "уже/да уж" },
  { id: 3,  word: "valjda",  uk: "мабуть",          ru: "наверное" },
  { id: 4,  word: "eto",     uk: "ось/от",          ru: "вот" },
  { id: 5,  word: "pa",      uk: "та/же",           ru: "да/же" },
  { id: 6,  word: "ma",      uk: "та/та ну",        ru: "да/да ну" },
  { id: 7,  word: "tek",     uk: "лише/тільки",     ru: "лишь/только" },
  { id: 8,  word: "još",     uk: "ще",              ru: "ещё" },
  { id: 9,  word: "evo",     uk: "ось",             ru: "вот (же)" },
  { id: 10, word: "eno",     uk: "он там",          ru: "вон там" }
];

// === ADVERBS ===
window.decks.de_adverbs = [
  { id: 1,  word: "sada",       uk: "зараз",        ru: "сейчас" },
  { id: 2,  word: "već",        uk: "вже",          ru: "уже" },
  { id: 3,  word: "još",        uk: "ще",           ru: "ещё" },
  { id: 4,  word: "samo",       uk: "тільки",       ru: "только" },
  { id: 5,  word: "takođe",     uk: "також",        ru: "тоже" },
  { id: 6,  word: "vrlo",       uk: "дуже",         ru: "очень" },
  { id: 7,  word: "uvek",       uk: "завжди",       ru: "всегда" },
  { id: 8,  word: "nikad",      uk: "ніколи",       ru: "никогда" },
  { id: 9,  word: "ponekad",    uk: "іноді",        ru: "иногда" },
  { id: 10, word: "često",      uk: "часто",        ru: "часто" },
  { id: 11, word: "retko",      uk: "рідко",        ru: "редко" },
  { id: 12, word: "uskoro",     uk: "незабаром",    ru: "скоро" },
  { id: 13, word: "odmah",      uk: "відразу",      ru: "сразу" },
  { id: 14, word: "danas",      uk: "сьогодні",     ru: "сегодня" },
  { id: 15, word: "juče",       uk: "вчора",        ru: "вчера" },
  { id: 16, word: "sutra",      uk: "завтра",       ru: "завтра" },
  { id: 17, word: "prekosutra", uk: "післязавтра",  ru: "послезавтра" },
  { id: 18, word: "prekjuče",   uk: "позавчора",    ru: "позавчера" },
  { id: 19, word: "ranije",     uk: "раніше",       ru: "раньше" },
  { id: 20, word: "kasnije",    uk: "пізніше",      ru: "позже" },
  { id: 21, word: "tada",       uk: "тоді",         ru: "тогда" },
  { id: 22, word: "iznenada",   uk: "раптом",       ru: "вдруг" },
  { id: 23, word: "napokon",    uk: "нарешті",      ru: "наконец" },
  { id: 24, word: "verovatno",  uk: "ймовірно",     ru: "вероятно" },
  { id: 25, word: "možda",      uk: "можливо",      ru: "может быть" },
  { id: 26, word: "sigurno",    uk: "напевно",      ru: "точно/наверняка" },
  { id: 27, word: "baš",        uk: "саме",         ru: "именно" },
  { id: 28, word: "tačno",      uk: "точно",        ru: "точно" },
  { id: 29, word: "rado",       uk: "охоче",        ru: "охотно" },
  { id: 30, word: "radije",     uk: "краще (волів би)", ru: "лучше (охотнее)" },
  { id: 31, word: "najradije",  uk: "найбільше",    ru: "больше всего" },
  { id: 32, word: "zajedno",    uk: "разом",        ru: "вместе" },
  { id: 33, word: "sami",       uk: "самі/наодинці",ru: "в одиночку" },
  { id: 34, word: "ovde",       uk: "тут",          ru: "здесь" },
  { id: 35, word: "tamo",       uk: "там",          ru: "там" },
  { id: 36, word: "tu",         uk: "тут/там",      ru: "здесь/там" },
  { id: 37, word: "svuda",      uk: "скрізь",       ru: "везде" },
  { id: 38, word: "negde",      uk: "десь",         ru: "где-то" },
  { id: 39, word: "nigde",      uk: "ніде",         ru: "нигде" },
  { id: 40, word: "gore",       uk: "вгору/нагорі", ru: "наверху" },
  { id: 41, word: "dole",       uk: "вниз/внизу",   ru: "внизу" },
  { id: 42, word: "unutra",     uk: "всередині",    ru: "внутри" },
  { id: 43, word: "napolju",    uk: "зовні",        ru: "снаружи" },
  { id: 44, word: "levo",       uk: "ліворуч",      ru: "налево" },
  { id: 45, word: "desno",      uk: "праворуч",     ru: "направо" },
  { id: 46, word: "napred",     uk: "вперед",       ru: "вперёд" },
  { id: 47, word: "pozadi",     uk: "позаду",       ru: "сзади" },
  { id: 48, word: "dalje",      uk: "далі",         ru: "дальше" },
  { id: 49, word: "upravo",     uk: "щойно/саме",   ru: "только что/как раз" },
  { id: 50, word: "tako",       uk: "так/таким чином", ru: "так/таким образом" },
  { id: 51, word: "drugačije",  uk: "інакше",       ru: "по-другому" },
  { id: 52, word: "isto",       uk: "так само",     ru: "так же" },
  { id: 53, word: "dovoljno",   uk: "достатньо",    ru: "достаточно" },
  { id: 54, word: "prilično",   uk: "досить",       ru: "довольно" },
  { id: 55, word: "potpuno",    uk: "повністю",     ru: "полностью" },
  { id: 56, word: "uopšte",     uk: "взагалі",      ru: "вообще" },
  { id: 57, word: "ponovo",     uk: "знову",        ru: "снова" },
  { id: 58, word: "zatim",      uk: "потім",        ru: "затем" },
  { id: 59, word: "onda",       uk: "тоді/потім",   ru: "тогда/потом" },
  { id: 60, word: "odande",     uk: "звідти",       ru: "оттуда" }
];

// === ADJECTIVES ===
window.decks.de_adjectives = [
  { id: 1,  word: "dobar",       uk: "добрий",        ru: "хороший" },
  { id: 2,  word: "loš",         uk: "поганий",       ru: "плохой" },
  { id: 3,  word: "veliki",      uk: "великий",       ru: "большой" },
  { id: 4,  word: "mali",        uk: "малий",         ru: "маленький" },
  { id: 5,  word: "lep",         uk: "гарний",        ru: "красивый" },
  { id: 6,  word: "ružan",       uk: "потворний",     ru: "уродливый" },
  { id: 7,  word: "nov",         uk: "новий",         ru: "новый" },
  { id: 8,  word: "star",        uk: "старий",        ru: "старый" },
  { id: 9,  word: "mlad",        uk: "молодий",       ru: "молодой" },
  { id: 10, word: "jednostavan", uk: "простий",       ru: "простой" },
  { id: 11, word: "težak",       uk: "важкий/складний", ru: "тяжёлый/сложный" },
  { id: 12, word: "lak",         uk: "легкий",        ru: "лёгкий" },
  { id: 13, word: "brz",         uk: "швидкий",       ru: "быстрый" },
  { id: 14, word: "spor",        uk: "повільний",     ru: "медленный" },
  { id: 15, word: "rani",        uk: "ранній",        ru: "ранний" },
  { id: 16, word: "kasni",       uk: "пізній",        ru: "поздний" },
  { id: 17, word: "vruć",        uk: "гарячий",       ru: "горячий" },
  { id: 18, word: "hladan",      uk: "холодний",      ru: "холодный" },
  { id: 19, word: "topao",       uk: "теплий",        ru: "тёплый" },
  { id: 20, word: "prijatan",    uk: "приємний",      ru: "приятный" },
  { id: 21, word: "ljubazan",    uk: "люб’язний",     ru: "вежливый" },
  { id: 22, word: "neljubazan",  uk: "неввічливий",   ru: "невежливый" },
  { id: 23, word: "srećan",      uk: "щасливий",      ru: "счастливый" },
  { id: 24, word: "tužan",       uk: "сумний",        ru: "грустный" },
  { id: 25, word: "tih",         uk: "тихий",         ru: "тихий" },
  { id: 26, word: "glasan",      uk: "гучний",        ru: "громкий" },
  { id: 27, word: "jak",         uk: "сильний",       ru: "сильный" },
  { id: 28, word: "slab",        uk: "слабкий",       ru: "слабый" },
  { id: 29, word: "zdrav",       uk: "здоровий",      ru: "здоровый" },
  { id: 30, word: "bolestan",    uk: "хворий",        ru: "больной" },
  { id: 31, word: "bogat",       uk: "багатий",       ru: "богатый" },
  { id: 32, word: "siromašan",   uk: "бідний",        ru: "бедный" },
  { id: 33, word: "skup",        uk: "дорогий",       ru: "дорогой" },
  { id: 34, word: "jeftin",      uk: "дешевий",       ru: "дешёвый" },
  { id: 35, word: "svetao",      uk: "світлий",       ru: "светлый" },
  { id: 36, word: "taman",       uk: "темний",        ru: "тёмный" },
  { id: 37, word: "blizak",      uk: "близький",      ru: "близкий" },
  { id: 38, word: "dalek",       uk: "далекий",       ru: "далёкий" },
  { id: 39, word: "tačan",       uk: "точний",        ru: "точный" },
  { id: 40, word: "pogrešan",    uk: "неправильний",  ru: "неправильный" },
  { id: 41, word: "poznat",      uk: "відомий",       ru: "известный" },
  { id: 42, word: "nepoznat",    uk: "невідомий",     ru: "неизвестный" },
  { id: 43, word: "slobodan",    uk: "вільний",       ru: "свободный" },
  { id: 44, word: "zauzet",      uk: "зайнятий",      ru: "занятый" },
  { id: 45, word: "otvoren",     uk: "відкритий",     ru: "открытый" },
  { id: 46, word: "zatvoren",    uk: "закритий",      ru: "закрытый" },
  { id: 47, word: "zanimljiv",   uk: "цікавий",       ru: "интересный" },
  { id: 48, word: "dosadan",     uk: "нудний",        ru: "скучный" },
  { id: 49, word: "važan",       uk: "важливий",      ru: "важный" },
  { id: 50, word: "beznačajan",  uk: "неважливий",    ru: "неважный" },
  { id: 51, word: "siguran",     uk: "безпечний/надійний", ru: "надёжный/безопасный" },
  { id: 52, word: "nesiguran",   uk: "небезпечний",   ru: "ненадёжный/опасный" },
  { id: 53, word: "vredan",      uk: "працьовитий/цінний", ru: "трудолюбивый/ценный" },
  { id: 54, word: "lenj",        uk: "ледачий",       ru: "ленивый" },
  { id: 55, word: "umoran",      uk: "втомлений",     ru: "уставший" },
  { id: 56, word: "budan",       uk: "бадьорий",      ru: "бодрый" },
  { id: 57, word: "visok",       uk: "високий",       ru: "высокий" },
  { id: 58, word: "nizak",       uk: "низький",       ru: "низкий" },
  { id: 59, word: "dubok",       uk: "глибокий",      ru: "глубокий" },
  { id: 60, word: "plitak",      uk: "плаский",       ru: "мелкий" },
  { id: 61, word: "gladan",      uk: "голодний",      ru: "голодный" },
  { id: 62, word: "žedan",       uk: "спраглий",      ru: "жаждущий" },
  { id: 63, word: "sit",         uk: "ситий",         ru: "сытый" },
  { id: 64, word: "kriv",        uk: "винний",        ru: "виновный" },
  { id: 65, word: "nevin",       uk: "невинний",      ru: "невиновный" },
  { id: 66, word: "koristan",    uk: "корисний",      ru: "полезный" },
  { id: 67, word: "beskoristan", uk: "марний",        ru: "бесполезный" },
  { id: 68, word: "stvaran",     uk: "справжній",     ru: "реальный" },
  { id: 69, word: "čudan",       uk: "дивний",        ru: "странный" },
  { id: 70, word: "tipičan",     uk: "типовий",       ru: "типичный" },
  { id: 71, word: "službeni",    uk: "офіційний",     ru: "официальный" },
  { id: 72, word: "privatan",    uk: "приватний",     ru: "частный" },
  { id: 73, word: "pametan",     uk: "розумний",      ru: "умный" },
  { id: 74, word: "glup",        uk: "дурний",        ru: "глупый" },
  { id: 75, word: "kratak",      uk: "короткий",      ru: "короткий" },
  { id: 76, word: "dugačak",     uk: "довгий",        ru: "длинный" },
  { id: 77, word: "novčan",      uk: "грошовий",      ru: "денежный" },
  { id: 78, word: "radan",       uk: "робочий/працьовитий", ru: "рабочий/трудолюбивый" },
  { id: 79, word: "važan",       uk: "важливий",      ru: "важный" },
  { id: 80, word: "besmislen",   uk: "безглуздий",    ru: "бессмысленный" }
];

// === NOUNS ===
window.decks.de_nouns = [
  { id: 1,   word: "novac",           uk: "гроші",                 ru: "деньги" },
  { id: 2,   word: "vreme",           uk: "час/погода",            ru: "время/погода" },
  { id: 3,   word: "godina",          uk: "рік",                   ru: "год" },
  { id: 4,   word: "čovek",           uk: "людина",                ru: "человек" },
  { id: 5,   word: "žena",            uk: "жінка",                 ru: "женщина" },
  { id: 6,   word: "muškarac",        uk: "чоловік",               ru: "мужчина" },
  { id: 7,   word: "dete",            uk: "дитина",                ru: "ребёнок" },
  { id: 8,   word: "grad",            uk: "місто",                 ru: "город" },
  { id: 9,   word: "zemlja",          uk: "країна/земля",          ru: "страна/земля" },
  { id: 10,  word: "kuća",            uk: "будинок",               ru: "дом" },

  { id: 11,  word: "stan",            uk: "квартира",              ru: "квартира" },
  { id: 12,  word: "soba",            uk: "кімната",               ru: "комната" },
  { id: 13,  word: "vrata",           uk: "двері",                 ru: "дверь" },
  { id: 14,  word: "prozor",          uk: "вікно",                 ru: "окно" },
  { id: 15,  word: "sto",             uk: "стіл",                  ru: "стол" },
  { id: 16,  word: "stolica",         uk: "стілець",               ru: "стул" },
  { id: 17,  word: "krevet",          uk: "ліжко",                 ru: "кровать" },
  { id: 18,  word: "ormar",           uk: "шафа",                  ru: "шкаф" },
  { id: 19,  word: "lampa",           uk: "лампа",                 ru: "лампа" },
  { id: 20,  word: "tepih",           uk: "килим",                 ru: "ковёр" },

  { id: 21,  word: "auto",            uk: "авто",                  ru: "машина" },
  { id: 22,  word: "autobus",         uk: "автобус",               ru: "автобус" },
  { id: 23,  word: "voz",             uk: "поїзд",                 ru: "поезд" },
  { id: 24,  word: "avion",           uk: "літак",                 ru: "самолёт" },
  { id: 25,  word: "brod",            uk: "корабель",              ru: "корабль" },
  { id: 26,  word: "bicikl",          uk: "велосипед",             ru: "велосипед" },
  { id: 27,  word: "ulica",           uk: "вулиця",                ru: "улица" },
  { id: 28,  word: "most",            uk: "міст",                  ru: "мост" },
  { id: 29,  word: "put",             uk: "шлях/дорога",           ru: "путь/дорога" },
  { id: 30,  word: "trg",             uk: "площа",                 ru: "площадь" },

  { id: 31,  word: "voda",            uk: "вода",                  ru: "вода" },
  { id: 32,  word: "hleb",            uk: "хліб",                  ru: "хлеб" },
  { id: 33,  word: "mleko",           uk: "молоко",                ru: "молоко" },
  { id: 34,  word: "sir",             uk: "сир",                   ru: "сыр" },
  { id: 35,  word: "meso",            uk: "м’ясо",                 ru: "мясо" },
  { id: 36,  word: "riba",            uk: "риба",                  ru: "рыба" },
  { id: 37,  word: "povrće",          uk: "овочі",                 ru: "овощи" },
  { id: 38,  word: "voće",            uk: "фрукти",                ru: "фрукты" },
  { id: 39,  word: "jabuka",          uk: "яблуко",                ru: "яблоко" },
  { id: 40,  word: "banana",          uk: "банан",                 ru: "банан" },

  { id: 41,  word: "posao",           uk: "робота",                ru: "работа" },
  { id: 42,  word: "zanimanje",       uk: "професія",              ru: "профессия" },
  { id: 43,  word: "škola",           uk: "школа",                 ru: "школа" },
  { id: 44,  word: "univerzitet",     uk: "університет",           ru: "университет" },
  { id: 45,  word: "učitelj",         uk: "вчитель",               ru: "учитель" },
  { id: 46,  word: "učenik",          uk: "учень",                 ru: "ученик" },
  { id: 47,  word: "student",         uk: "студент",               ru: "студент" },
  { id: 48,  word: "knjiga",          uk: "книга",                 ru: "книга" },
  { id: 49,  word: "novine",          uk: "газета",                ru: "газета" },
  { id: 50,  word: "sveska",          uk: "зошит",                 ru: "тетрадь" },

  { id: 51,  word: "računar",         uk: "комп’ютер",             ru: "компьютер" },
  { id: 52,  word: "laptop",          uk: "ноутбук",               ru: "ноутбук" },
  { id: 53,  word: "telefon",         uk: "телефон",               ru: "телефон" },
  { id: 54,  word: "internet",        uk: "інтернет",              ru: "интернет" },
  { id: 55,  word: "monitor",         uk: "екран/монітор",         ru: "экран/монитор" },
  { id: 56,  word: "miš",             uk: "миша",                  ru: "мышь" },
  { id: 57,  word: "tastatura",       uk: "клавіатура",            ru: "клавиатура" },
  { id: 58,  word: "štampač",         uk: "принтер",               ru: "принтер" },
  { id: 59,  word: "aplikacija",      uk: "додаток",               ru: "приложение" },
  { id: 60,  word: "program",         uk: "програма",              ru: "программа" },

  { id: 61,  word: "porodica",        uk: "родина",                ru: "семья" },
  { id: 62,  word: "otac",            uk: "батько",                ru: "отец" },
  { id: 63,  word: "majka",           uk: "мати",                  ru: "мать" },
  { id: 64,  word: "sin",             uk: "син",                   ru: "сын" },
  { id: 65,  word: "ćerka",           uk: "дочка",                 ru: "дочь" },
  { id: 66,  word: "brat",            uk: "брат",                  ru: "брат" },
  { id: 67,  word: "sestra",          uk: "сестра",                ru: "сестра" },
  { id: 68,  word: "prijatelj",       uk: "друг",                  ru: "друг" },
  { id: 69,  word: "prijateljica",    uk: "подруга",               ru: "подруга" },
  { id: 70,  word: "roditelji",       uk: "батьки",                ru: "родители" },

  { id: 71,  word: "hrana",           uk: "їжа",                   ru: "еда" },
  { id: 72,  word: "doručak",         uk: "сніданок",              ru: "завтрак" },
  { id: 73,  word: "ručak",           uk: "обід",                  ru: "обед" },
  { id: 74,  word: "večera",          uk: "вечеря",                ru: "ужин" },
  { id: 75,  word: "piće",            uk: "напій",                 ru: "напиток" },
  { id: 76,  word: "sok",             uk: "сік",                   ru: "сок" },
  { id: 77,  word: "čaj",             uk: "чай",                   ru: "чай" },
  { id: 78,  word: "kafa",            uk: "кава",                  ru: "кофе" },
  { id: 79,  word: "pivo",            uk: "пиво",                  ru: "пиво" },
  { id: 80,  word: "vino",            uk: "вино",                  ru: "вино" },

  { id: 81,  word: "lekar",           uk: "лікар",                 ru: "врач" },
  { id: 82,  word: "klinika",         uk: "клініка",               ru: "клиника" },
  { id: 83,  word: "bolnica",         uk: "лікарня",               ru: "больница" },
  { id: 84,  word: "tableta",         uk: "таблетка",              ru: "таблетка" },
  { id: 85,  word: "lek",             uk: "ліки",                  ru: "лекарство" },
  { id: 86,  word: "zdravlje",        uk: "здоров’я",              ru: "здоровье" },
  { id: 87,  word: "bolest",          uk: "хвороба",               ru: "болезнь" },
  { id: 88,  word: "bol",             uk: "біль",                  ru: "боль" },
  { id: 89,  word: "pomoć",           uk: "допомога",              ru: "помощь" },
  { id: 90,  word: "osiguranje",      uk: "страхування",           ru: "страховка" },

  { id: 91,  word: "sunce",           uk: "сонце",                 ru: "солнце" },
  { id: 92,  word: "mesec",           uk: "місяць",                ru: "луна/місяць" },
  { id: 93,  word: "zvezda",          uk: "зірка",                 ru: "звезда" },
  { id: 94,  word: "kiša",            uk: "дощ",                   ru: "дождь" },
  { id: 95,  word: "sneg",            uk: "сніг",                  ru: "снег" },
  { id: 96,  word: "vetar",           uk: "вітер",                 ru: "ветер" },
  { id: 97,  word: "oblak",           uk: "хмара",                 ru: "облако" },
  { id: 98,  word: "nebo",            uk: "небо",                  ru: "небо" },
  { id: 99,  word: "temperatura",     uk: "температура",           ru: "температура" },
  { id: 100, word: "proleće",         uk: "весна",                 ru: "весна" },

  { id: 101, word: "leto",            uk: "літо",                  ru: "лето" },
  { id: 102, word: "jesen",           uk: "осінь",                 ru: "осень" },
  { id: 103, word: "zima",            uk: "зима",                  ru: "зима" },
  { id: 104, word: "nedelja",         uk: "тиждень/неділя",        ru: "неделя/воскресенье" },
  { id: 105, word: "ponedeljak",      uk: "понеділок",             ru: "понедельник" },
  { id: 106, word: "utorak",          uk: "вівторок",              ru: "вторник" },
  { id: 107, word: "sreda",           uk: "середа",                ru: "среда" },
  { id: 108, word: "četvrtak",        uk: "четвер",                ru: "четверг" },
  { id: 109, word: "petak",           uk: "п’ятниця",              ru: "пятница" },
  { id: 110, word: "subota",          uk: "субота",                ru: "суббота" },

  { id: 111, word: "nedelja (день)",  uk: "неділя (день)",         ru: "воскресенье" },
  { id: 112, word: "glava",           uk: "голова",                ru: "голова" },
  { id: 113, word: "lice",            uk: "обличчя",               ru: "лицо" },
  { id: 114, word: "oko",             uk: "око/очі",               ru: "глаз" },
  { id: 115, word: "nos",             uk: "ніс",                   ru: "нос" },
  { id: 116, word: "usta",            uk: "рот",                   ru: "рот" },
  { id: 117, word: "uho",             uk: "вухо",                  ru: "ухо" },
  { id: 118, word: "vrat",            uk: "шия",                   ru: "шея" },
  { id: 119, word: "rame",            uk: "плече",                 ru: "плечо" },
  { id: 120, word: "ruka",            uk: "рука/долоня",           ru: "рука/ладонь" },

  { id: 121, word: "prst",            uk: "палець",                ru: "палец" },
  { id: 122, word: "noga",            uk: "нога",                  ru: "нога" },
  { id: 123, word: "koleno",          uk: "коліно",                ru: "колено" },
  { id: 124, word: "stopalo",         uk: "ступня",                ru: "ступня" },
  { id: 125, word: "srce",            uk: "серце",                 ru: "сердце" },
  { id: 126, word: "krv",             uk: "кров",                  ru: "кровь" },
  { id: 127, word: "telo",            uk: "тіло",                  ru: "тело" },
  { id: 128, word: "glad",            uk: "голод",                 ru: "голод" },
  { id: 129, word: "žeđ",             uk: "спрага",                ru: "жажда" },
  { id: 130, word: "umor",            uk: "втома",                 ru: "усталость" },

  { id: 131, word: "kuvar",           uk: "кухар",                 ru: "повар" },
  { id: 132, word: "konobar",         uk: "офіціант",              ru: "официант" },
  { id: 133, word: "prodavac",        uk: "продавець",             ru: "продавец" },
  { id: 134, word: "vozač",           uk: "водій",                 ru: "водитель" },
  { id: 135, word: "inženjer",        uk: "інженер",               ru: "инженер" },
  { id: 136, word: "programer",       uk: "програміст",            ru: "программист" },
  { id: 137, word: "menadžer",        uk: "менеджер",              ru: "менеджер" },
  { id: 138, word: "račun",           uk: "рахунок",               ru: "счёт" },
  { id: 139, word: "karta",           uk: "квиток/карта",          ru: "билет/карта" },
  { id: 140, word: "ulaz",            uk: "вхід",                  ru: "вход" },

  { id: 141, word: "izlaz",           uk: "вихід",                 ru: "выход" },
  { id: 142, word: "pomoćnik",        uk: "помічник",              ru: "помощник" },
  { id: 143, word: "gazda",           uk: "хазяїн/власник",        ru: "хозяин/владелец" },
  { id: 144, word: "gost",            uk: "гість",                 ru: "гость" },
  { id: 145, word: "stanica",         uk: "станція",               ru: "станция" },
  { id: 146, word: "aerodrom",        uk: "аеропорт",              ru: "аэропорт" },
  { id: 147, word: "taksi",           uk: "таксі",                 ru: "такси" },
  { id: 148, word: "vožnja",          uk: "їзда/поездка",          ru: "поездка" },
  { id: 149, word: "let",             uk: "політ",                 ru: "полёт" },
  { id: 150, word: "putovanje",       uk: "подорож",               ru: "путешествие" },

  { id: 151, word: "ulaznica",        uk: "квиток (вхід)",         ru: "входной билет" },
  { id: 152, word: "red",             uk: "черга/порядок",         ru: "очередь/порядок" },
  { id: 153, word: "cena",            uk: "ціна",                  ru: "цена" },
  { id: 154, word: "novčanik",        uk: "гаманець",              ru: "кошелёк" },
  { id: 155, word: "kartica",         uk: "картка",                ru: "карта (платёжная)" },
  { id: 156, word: "prodavnica",      uk: "крамниця/магазин",      ru: "магазин" },
  { id: 157, word: "market",          uk: "ринок/маркет",          ru: "рынок/маркет" },
  { id: 158, word: "tržni centar",    uk: "торговий центр",        ru: "торговый центр" },
  { id: 159, word: "polica",          uk: "полиця",                ru: "полка" },
  { id: 160, word: "kesa",            uk: "пакет",                 ru: "пакет" },

  { id: 161, word: "gradilište",      uk: "будмайданчик",          ru: "стройплощадка" },
  { id: 162, word: "zgrada",          uk: "будівля",               ru: "здание" },
  { id: 163, word: "lift",            uk: "ліфт",                  ru: "лифт" },
  { id: 164, word: "stepenice",       uk: "сходи",                 ru: "лестница" },
  { id: 165, word: "vrtić",           uk: "дитсадок",              ru: "детсад" },
  { id: 166, word: "bolesnik",        uk: "хворий (людина)",       ru: "больной (чел.)" },
  { id: 167, word: "kupatilo",        uk: "ванна кімната",         ru: "ванная" },
  { id: 168, word: "kuhinja",         uk: "кухня",                 ru: "кухня" },
  { id: 169, word: "dnevna soba",     uk: "вітальня",              ru: "гостиная" },
  { id: 170, word: "spavaća soba",    uk: "спальня",               ru: "спальня" },

  { id: 171, word: "frižider",        uk: "холодильник",           ru: "холодильник" },
  { id: 172, word: "šporet",          uk: "плита",                 ru: "плита" },
  { id: 173, word: "sudopera",        uk: "мийка",                 ru: "раковина (кух.)" },
  { id: 174, word: "mašina za veš",   uk: "пральна машина",        ru: "стиральная машина" },
  { id: 175, word: "usisivač",        uk: "пилосос",               ru: "пылесос" },
  { id: 176, word: "pegla",           uk: "праска",                ru: "утюг" },
  { id: 177, word: "daljinski",       uk: "пульт",                 ru: "пульт" },
  { id: 178, word: "punjač",          uk: "зарядний пристрій",     ru: "зарядное устройство" },
  { id: 179, word: "kabl",            uk: "кабель",                ru: "кабель" },
  { id: 180, word: "utičnica",        uk: "розетка",               ru: "розетка" },

  { id: 181, word: "dokument",        uk: "документ",              ru: "документ" },
  { id: 182, word: "ugovor",          uk: "договір",               ru: "договор" },
  { id: 183, word: "potpis",          uk: "підпис",                ru: "подпись" },
  { id: 184, word: "pošta",           uk: "пошта",                 ru: "почта" },
  { id: 185, word: "paket",           uk: "пакунок/посилка",       ru: "посылка" },
  { id: 186, word: "poruka",          uk: "повідомлення",          ru: "сообщение" },
  { id: 187, word: "poziv",           uk: "дзвінок/запрошення",    ru: "звонок/приглашение" },
  { id: 188, word: "sastanak",        uk: "зустріч",               ru: "встреча" },
  { id: 189, word: "dogovor",         uk: "домовленість",          ru: "договорённость" },
  { id: 190, word: "razgovor",        uk: "розмова",               ru: "разговор" },

  { id: 191, word: "ideja",           uk: "ідея",                  ru: "идея" },
  { id: 192, word: "plan",            uk: "план",                  ru: "план" },
  { id: 193, word: "cilj",            uk: "мета",                  ru: "цель" },
  { id: 194, word: "problem",         uk: "проблема",              ru: "проблема" },
  { id: 195, word: "rešenje",         uk: "рішення/вирішення",     ru: "решение" },
  { id: 196, word: "uslov",           uk: "умова",                 ru: "условие" },
  { id: 197, word: "pravilo",         uk: "правило",               ru: "правило" },
  { id: 198, word: "primer",          uk: "приклад",               ru: "пример" },
  { id: 199, word: "pitanje",         uk: "питання",               ru: "вопрос" },
  { id: 200, word: "odgovor",         uk: "відповідь",             ru: "ответ" }
];

// === VERBS ===
window.decks.de_verbs = [
  { id: 1,   word: "biti",        uk: "бути",             ru: "быть" },
  { id: 2,   word: "imati",       uk: "мати",             ru: "иметь" },
  { id: 3,   word: "raditi",      uk: "працювати/робити", ru: "работать/делать" },
  { id: 4,   word: "reći",        uk: "сказати",          ru: "сказать" },
  { id: 5,   word: "govoriti",    uk: "говорити",         ru: "говорить" },
  { id: 6,   word: "videti",      uk: "бачити",           ru: "видеть" },
  { id: 7,   word: "gledati",     uk: "дивитися",         ru: "смотреть" },
  { id: 8,   word: "čuti",        uk: "чути",             ru: "слышать" },
  { id: 9,   word: "slušati",     uk: "слухати",          ru: "слушать" },
  { id: 10,  word: "znati",       uk: "знати",            ru: "знать" },

  { id: 11,  word: "moći",        uk: "могти",            ru: "мочь" },
  { id: 12,  word: "želeti",      uk: "хотіти/бажати",    ru: "хотеть/желать" },
  { id: 13,  word: "voleti",      uk: "любити",           ru: "любить" },
  { id: 14,  word: "misliti",     uk: "думати",           ru: "думать" },
  { id: 15,  word: "znati",       uk: "знати",            ru: "уметь/знать" },
  { id: 16,  word: "verovati",    uk: "вірити",           ru: "верить" },
  { id: 17,  word: "nadati se",   uk: "сподіватися",      ru: "надеяться" },
  { id: 18,  word: "plašiti se",  uk: "боятися",          ru: "бояться" },
  { id: 19,  word: "sećati se",   uk: "пам’ятати",        ru: "помнить" },
  { id: 20,  word: "zaboraviti",  uk: "забути",           ru: "забыть" },

  { id: 21,  word: "jesti",       uk: "їсти",             ru: "есть" },
  { id: 22,  word: "piti",        uk: "пити",             ru: "пить" },
  { id: 23,  word: "spavati",     uk: "спати",            ru: "спать" },
  { id: 24,  word: "ustati",      uk: "встати",           ru: "встать" },
  { id: 25,  word: "ležati",      uk: "лежати",           ru: "лежать" },
  { id: 26,  word: "sedeti",      uk: "сидіти",           ru: "сидеть" },
  { id: 27,  word: "stajati",     uk: "стояти",           ru: "стоять" },
  { id: 28,  word: "hodati",      uk: "ходити (пішки)",   ru: "ходить" },
  { id: 29,  word: "trčati",      uk: "бігти",            ru: "бежать" },
  { id: 30,  word: "ići",         uk: "йти",              ru: "идти/ехать" },

  { id: 31,  word: "doći",        uk: "прийти",           ru: "прийти" },
  { id: 32,  word: "otići",       uk: "піти/піти геть",   ru: "уйти" },
  { id: 33,  word: "ulaziti",     uk: "заходити",         ru: "входить" },
  { id: 34,  word: "izlaziti",    uk: "виходити",         ru: "выходить" },
  { id: 35,  word: "nositi",      uk: "носити",           ru: "носить" },
  { id: 36,  word: "doneti",      uk: "принести",         ru: "принести" },
  { id: 37,  word: "odneti",      uk: "віднести",         ru: "унести/отнести" },
  { id: 38,  word: "voziti",      uk: "керувати/вести",   ru: "водить (машину)" },
  { id: 39,  word: "voziti se",   uk: "їхати",            ru: "ехать" },
  { id: 40,  word: "putovati",    uk: "подорожувати",     ru: "путешествовать" },

  { id: 41,  word: "raditi",      uk: "робити/працювати", ru: "делать/работать" },
  { id: 42,  word: "praviti",     uk: "робити/створювати",ru: "делать/создавать" },
  { id: 43,  word: "kupiti",      uk: "купити",           ru: "купить" },
  { id: 44,  word: "prodati",     uk: "продати",          ru: "продать" },
  { id: 45,  word: "platiti",     uk: "заплатити",        ru: "заплатить" },
  { id: 46,  word: "dobiti",      uk: "отримати",         ru: "получить" },
  { id: 47,  word: "dati",        uk: "дати",             ru: "дать" },
  { id: 48,  word: "uzeti",       uk: "взяти",            ru: "взять" },
  { id: 49,  word: "otvoriti",    uk: "відкрити",         ru: "открыть" },
  { id: 50,  word: "zatvoriti",   uk: "закрити",          ru: "закрыть" },

  { id: 51,  word: "čitati",      uk: "читати",           ru: "читать" },
  { id: 52,  word: "pisati",      uk: "писати",           ru: "писать" },
  { id: 53,  word: "učiti",       uk: "вчити",            ru: "учить" },
  { id: 54,  word: "naučiti",     uk: "вивчити",          ru: "выучить" },
  { id: 55,  word: "pamtiti",     uk: "пам’ятати",        ru: "запоминать" },
  { id: 56,  word: "pitati",      uk: "питати",           ru: "спрашивать" },
  { id: 57,  word: "odgovoriti",  uk: "відповісти",       ru: "ответить" },
  { id: 58,  word: "objasniti",   uk: "пояснити",         ru: "объяснить" },
  { id: 59,  word: "razumeti",    uk: "розуміти",         ru: "понимать" },
  { id: 60,  word: "znati",       uk: "знати",            ru: "знать" },

  { id: 61,  word: "igrati",      uk: "грати",            ru: "играть" },
  { id: 62,  word: "plesati",     uk: "танцювати",        ru: "танцевать" },
  { id: 63,  word: "pevati",      uk: "співати",          ru: "петь" },
  { id: 64,  word: "gledati",     uk: "дивитися",         ru: "смотреть" },
  { id: 65,  word: "svirati",     uk: "грати (на інстр.)",ru: "играть (на муз. инструменте)" },
  { id: 66,  word: "kuvati",      uk: "готувати",         ru: "готовить" },
  { id: 67,  word: "čistiti",     uk: "чистити",          ru: "чистить/убирать" },
  { id: 68,  word: "prati",       uk: "мити/прати",       ru: "мыть/стирать" },
  { id: 69,  word: "sušiti",      uk: "сушити",           ru: "сушить" },
  { id: 70,  word: "peći",        uk: "пекти",            ru: "печь" },

  { id: 71,  word: "početi",      uk: "почати",           ru: "начать" },
  { id: 72,  word: "završiti",    uk: "закінчити",        ru: "закончить" },
  { id: 73,  word: "trajati",     uk: "тривати",          ru: "длиться" },
  { id: 74,  word: "ostati",      uk: "залишитися",       ru: "остаться" },
  { id: 75,  word: "promeniti",   uk: "змінити",          ru: "изменить" },
  { id: 76,  word: "pokušati",    uk: "спробувати",       ru: "попробовать" },
  { id: 77,  word: "uspeti",      uk: "вдалося/успішно",  ru: "смочь/преуспеть" },
  { id: 78,  word: "pobediti",    uk: "перемогти",        ru: "победить" },
  { id: 79,  word: "izgubiti",    uk: "втратити/програти",ru: "потерять/проиграть" },
  { id: 80,  word: "naći",        uk: "знайти",           ru: "найти" },

  { id: 81,  word: "tražiti",     uk: "шукати",           ru: "искать" },
  { id: 82,  word: "čekati",      uk: "чекати",           ru: "ждать" },
  { id: 83,  word: "pozvati",     uk: "покликати/подзвонити", ru: "позвать/позвонить" },
  { id: 84,  word: "dozvoliti",   uk: "дозволити",        ru: "разрешить" },
  { id: 85,  word: "zabraniti",   uk: "заборонити",       ru: "запретить" },
  { id: 86,  word: "morati",      uk: "мусити",           ru: "долженствовать" },
  { id: 87,  word: "trebati",     uk: "потрібно",         ru: "нужно" },
  { id: 88,  word: "gledati",     uk: "дивитися",         ru: "смотреть" },
  { id: 89,  word: "čuvati",      uk: "берегти/охороняти",ru: "хранить/беречь" },
  { id: 90,  word: "koristiti",   uk: "користуватися",    ru: "использовать" },

  { id: 91,  word: "voziti",      uk: "водити",           ru: "водить" },
  { id: 92,  word: "leteti",      uk: "літати",           ru: "летать" },
  { id: 93,  word: "plivati",     uk: "плавати",          ru: "плавать" },
  { id: 94,  word: "pasti",       uk: "падати",           ru: "падать" },
  { id: 95,  word: "skočiti",     uk: "стрибнути",        ru: "прыгнуть" },
  { id: 96,  word: "držati",      uk: "тримати",          ru: "держать" },
  { id: 97,  word: "baciti",      uk: "кинути",           ru: "бросить" },
  { id: 98,  word: "udariti",     uk: "вдарити",          ru: "ударить" },
  { id: 99,  word: "pomeriti",    uk: "пересунути",       ru: "передвинуть" },
  { id: 100, word: "okrenuti",    uk: "повернути",        ru: "повернуть" }
];
